# Catálogo de Áreas Usuarias
LISTA_AREAS = [
    "🟡 DIRECCIÓN GENERAL DE OPERACIÓN",
    "🟢 GERENCIA DE INGENIERÍA Y NUEVOS PROYECTOS",
    "🔵 CAPITAL HUMANO",
    "🩷 COORDINACIÓN DE EVALUACIÓN DE PROYECTOS Y MANTENIMIENTO DE ÁREAS GENERALES",
    "🟠 DIRECCIÓN GENERAL DE ADMINISTRACIÓN Y FINANZAS",
    "🔴 DIRECCIÓN DE MANTENIMIENTO DE MATERIAL RODANTE",
    "🟣 DIRECCIÓN DE INSTALACIONES FIJAS",
    "⚫ DIRECCIÓN DE TRANSPORTACIÓN",
    "🟤 GERENCIA DE SEGURIDAD INSTITUCIONAL",
    "⚪ DIRECCIÓN DE MEDIOS",
    "🍷 GERENCIA DE ALMACENES Y SUMINISTROS",
    "🔘 GERENCIA DE SALUD Y BIENESTAR SOCIAL",
    "🌐 GERENCIA DE ORGANIZACIÓN Y SISTEMAS",
    "🩵 PREVIAS"
]
